version: '3'

networks:
    coopi:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: coopi_nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - coopi

    mariadb:
        image: mariadb:latest
        container_name: coopi_mariadb
        volumes:
            - ./docker/database:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=wordpress
            - MYSQL_DATABASE=wordpress
        networks:
            - coopi    

    php:
        build: ./docker/php
        container_name: coopi_php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"       
        networks:
            - coopi

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: coopi_phpmyadmin
        ports:
            - "8000:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        networks:
            - coopi